# Generated by Django 5.2.7 on 2025-10-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
