# Generated by Django 5.2.7 on 2025-10-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogitem_is_default_alter_blogitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='to_publish',
            field=models.BooleanField(default=True),
        ),
    ]
