# Generated by Django 5.2.7 on 2025-10-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_to_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogattachment',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
