# Generated by Django 5.2.7 on 2025-10-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projecttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttag'),
        ),
    ]
