# Generated by Django 5.2.7 on 2025-10-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
