# Generated by Django 5.2.7 on 2025-10-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectattachment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='to_publish',
            field=models.BooleanField(default=True),
        ),
    ]
